artifact_location: file:C:/Users/odhia/OneDrive/Desktop/datascienceproject/notebooks/Decision_tree_mlruns/877832777734984757
creation_time: 1720985122674
experiment_id: '877832777734984757'
last_update_time: 1720985122674
lifecycle_stage: active
name: tree_exp
