channels:
- conda-forge
dependencies:
- python=3.11.3
- pip<=22.3.1
- pip:
  - mlflow==2.14.3
  - cloudpickle==3.0.0
  - numpy==1.23.5
  - packaging==24.1
  - pandas==2.2.2
  - psutil==6.0.0
  - pyyaml==6.0.1
  - scikit-learn==1.5.1
  - scipy==1.10.1
  - xgboost==2.1.0
name: mlflow-env
