artifact_location: file:C:/Users/odhia/OneDrive/Desktop/datascienceproject/notebooks/xgb_mlruns/227920767218646985
creation_time: 1720985397309
experiment_id: '227920767218646985'
last_update_time: 1720985397309
lifecycle_stage: active
name: xgb_exp
