artifact_location: file:C:/Users/odhia/OneDrive/Desktop/datascienceproject/notebooks/logistic_mlruns/618839567731589264
creation_time: 1720984950305
experiment_id: '618839567731589264'
last_update_time: 1720984950305
lifecycle_stage: active
name: logistic_exp
