artifact_uri: file:C:/Users/odhia/OneDrive/Desktop/datascienceproject/notebooks/logistic_mlruns/618839567731589264/58a1a84709d24bfb8dee120e8faebee6/artifacts
end_time: 1720985029077
entry_point_name: ''
experiment_id: '618839567731589264'
lifecycle_stage: active
run_id: 58a1a84709d24bfb8dee120e8faebee6
run_name: logistic_run
run_uuid: 58a1a84709d24bfb8dee120e8faebee6
source_name: ''
source_type: 4
source_version: ''
start_time: 1720984953402
status: 3
tags: []
user_id: odhia
