artifact_location: file:C:/Users/odhia/OneDrive/Desktop/datascienceproject/notebooks/random_forest_mlruns/161028039202760377
creation_time: 1720985335606
experiment_id: '161028039202760377'
last_update_time: 1720985335606
lifecycle_stage: active
name: randomforest_exp
