artifact_location: file:C:/Users/odhia/OneDrive/Desktop/datascienceproject/notebooks/random_forest_mlruns/0
creation_time: 1720985335571
experiment_id: '0'
last_update_time: 1720985335571
lifecycle_stage: active
name: Default
