artifact_location: file:C:/Users/odhia/OneDrive/Desktop/datascienceproject/notebooks/Decision_tree_mlruns/0
creation_time: 1720985122507
experiment_id: '0'
last_update_time: 1720985122507
lifecycle_stage: active
name: Default
