artifact_location: file:C:/Users/odhia/OneDrive/Desktop/datascienceproject/notebooks/xgb_mlruns/0
creation_time: 1720985397283
experiment_id: '0'
last_update_time: 1720985397283
lifecycle_stage: active
name: Default
